

services:
  api:
    container_name: backend-lmarti-web-development-fullstack-docker
    image: image-backend-lmarti-web-development-fullstack-docker
    build: 
      context: .
    ports: 
      - 8100:8100
    depends_on:
      - mongo
    #volumes:
    #- .:/lmarti-web-development-fullstack-docker/backend

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"  
    volumes:
      - mongo-data:/data/db 

volumes:
  mongo-data: ~